/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mazerunner;

import static java.awt.Toolkit.getDefaultToolkit;
import java.awt.event.MouseEvent;
import static java.lang.Thread.sleep;

/**
 *
 * @author Dell
 */
public class stopwatch extends javax.swing.JFrame {
//private int hour;
int minute;
int second;
int csecond;
private boolean isStart;
int height, width;

    int count=0;
    String str;
    public stopwatch() {
        initComponents();
        width = (int) (getDefaultToolkit().getScreenSize().getHeight()/2);
        height = (int) (getDefaultToolkit().getScreenSize().getHeight()/2);
        
        this.setLocation(width + 200, 0);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        min = new javax.swing.JLabel();
        sec = new javax.swing.JLabel();
        csec = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 100));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        min.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        min.setForeground(new java.awt.Color(255, 255, 255));
        min.setText("00");
        jPanel1.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 90, -1));

        sec.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        sec.setForeground(new java.awt.Color(255, 255, 255));
        sec.setText("00");
        jPanel1.add(sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 100, -1));

        csec.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        csec.setForeground(new java.awt.Color(255, 255, 255));
        csec.setText("00");
        jPanel1.add(csec, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 80, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Min");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 50, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sec");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -10, 510, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void start() {
         //p3.setVisible(true);
      /*  start.setVisible(false);
         pause.setVisible(true); 
         p2.setVisible(false);
         p4.setVisible(false);
         reset.setVisible(true);*/
         
         isStart=true;
         
         Thread th=new Thread()
         {
            public void run()
            {
                
                while(isStart==true)
                {
                    try
                    {
                        sleep(9);
                    
                    csecond++;
                    if(csecond==100)
                    {
                        second++;
                        csecond=0;
                    }
                    if(second==60)
                    {
                        minute++;
                        second=0;
                    }
                       if(minute==60)
                    {
              
                        minute=0;
                    }
                   
                       min.setText("0"+minute);
                    if(second >=10) {
                        sec.setText(""+second);
                    }
                    else {
                        sec.setText("0"+second);
                    }
                    csec.setText(""+csecond);
                    }
                    catch(Exception ex)
                    {
                        System.out.print("something is wrong");
                    }
                }
            }
         };th.start();
         
    }
    
    public void stop() {
        isStart=false;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stopwatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stopwatch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel csec;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel min;
    private javax.swing.JLabel sec;
    // End of variables declaration//GEN-END:variables
}
